NEGATIVE_IMAGE = "Negative image"
THRESHOLDING = "Thresholding"
THRESHOLD_VALUE = "threshold_value"
LOG_FUNCTION_TRANSFORM = "Logarithmic Transformation"
INVERSE_LOG_FUNCTION_TRANSFORM = "Inverse logarithmic Transformation"